//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UD_Quan_Ly_Khach_San.BusinessServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLoaiPhong", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CLoaiPhong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UD_Quan_Ly_Khach_San.BusinessServiceRef.ExtensionDataObject ExtensionData1Field;
        
        private int _IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _TenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Ma_SoField;
        
        private int _Don_GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Tien_NghiField;
        
        private int _So_Khach_Toi_DaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ID {
            get {
                return this._IDField;
            }
            set {
                if ((this._IDField.Equals(value) != true)) {
                    this._IDField = value;
                    this.RaisePropertyChanged("_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string _Ten {
            get {
                return this._TenField;
            }
            set {
                if ((object.ReferenceEquals(this._TenField, value) != true)) {
                    this._TenField = value;
                    this.RaisePropertyChanged("_Ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _Ma_So {
            get {
                return this._Ma_SoField;
            }
            set {
                if ((object.ReferenceEquals(this._Ma_SoField, value) != true)) {
                    this._Ma_SoField = value;
                    this.RaisePropertyChanged("_Ma_So");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int _Don_Gia {
            get {
                return this._Don_GiaField;
            }
            set {
                if ((this._Don_GiaField.Equals(value) != true)) {
                    this._Don_GiaField = value;
                    this.RaisePropertyChanged("_Don_Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _Tien_Nghi {
            get {
                return this._Tien_NghiField;
            }
            set {
                if ((object.ReferenceEquals(this._Tien_NghiField, value) != true)) {
                    this._Tien_NghiField = value;
                    this.RaisePropertyChanged("_Tien_Nghi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int _So_Khach_Toi_Da {
            get {
                return this._So_Khach_Toi_DaField;
            }
            set {
                if ((this._So_Khach_Toi_DaField.Equals(value) != true)) {
                    this._So_Khach_Toi_DaField = value;
                    this.RaisePropertyChanged("_So_Khach_Toi_Da");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDouble", Namespace="http://tempuri.org/", ItemName="double")]
    [System.SerializableAttribute()]
    public class ArrayOfDouble : System.Collections.Generic.List<double> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CDoanhThuThang", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CDoanhThuThang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double _Doanh_Thu_LP1Field;
        
        private double _Doanh_Thu_LP2Field;
        
        private double _Doanh_Thu_LP3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double _Doanh_Thu_LP1 {
            get {
                return this._Doanh_Thu_LP1Field;
            }
            set {
                if ((this._Doanh_Thu_LP1Field.Equals(value) != true)) {
                    this._Doanh_Thu_LP1Field = value;
                    this.RaisePropertyChanged("_Doanh_Thu_LP1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double _Doanh_Thu_LP2 {
            get {
                return this._Doanh_Thu_LP2Field;
            }
            set {
                if ((this._Doanh_Thu_LP2Field.Equals(value) != true)) {
                    this._Doanh_Thu_LP2Field = value;
                    this.RaisePropertyChanged("_Doanh_Thu_LP2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double _Doanh_Thu_LP3 {
            get {
                return this._Doanh_Thu_LP3Field;
            }
            set {
                if ((this._Doanh_Thu_LP3Field.Equals(value) != true)) {
                    this._Doanh_Thu_LP3Field = value;
                    this.RaisePropertyChanged("_Doanh_Thu_LP3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPhong", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CPhong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UD_Quan_Ly_Khach_San.BusinessServiceRef.ExtensionDataObject ExtensionData1Field;
        
        private int _IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _TenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Ma_SoField;
        
        private int _ID_Loai_PhongField;
        
        private int _ID_TangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ID {
            get {
                return this._IDField;
            }
            set {
                if ((this._IDField.Equals(value) != true)) {
                    this._IDField = value;
                    this.RaisePropertyChanged("_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string _Ten {
            get {
                return this._TenField;
            }
            set {
                if ((object.ReferenceEquals(this._TenField, value) != true)) {
                    this._TenField = value;
                    this.RaisePropertyChanged("_Ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _Ma_So {
            get {
                return this._Ma_SoField;
            }
            set {
                if ((object.ReferenceEquals(this._Ma_SoField, value) != true)) {
                    this._Ma_SoField = value;
                    this.RaisePropertyChanged("_Ma_So");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int _ID_Loai_Phong {
            get {
                return this._ID_Loai_PhongField;
            }
            set {
                if ((this._ID_Loai_PhongField.Equals(value) != true)) {
                    this._ID_Loai_PhongField = value;
                    this.RaisePropertyChanged("_ID_Loai_Phong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int _ID_Tang {
            get {
                return this._ID_TangField;
            }
            set {
                if ((this._ID_TangField.Equals(value) != true)) {
                    this._ID_TangField = value;
                    this.RaisePropertyChanged("_ID_Tang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CKhachSan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CKhachSan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UD_Quan_Ly_Khach_San.BusinessServiceRef.ExtensionDataObject ExtensionData1Field;
        
        private int _IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _TenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Dien_ThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Dia_ChiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ID {
            get {
                return this._IDField;
            }
            set {
                if ((this._IDField.Equals(value) != true)) {
                    this._IDField = value;
                    this.RaisePropertyChanged("_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string _Ten {
            get {
                return this._TenField;
            }
            set {
                if ((object.ReferenceEquals(this._TenField, value) != true)) {
                    this._TenField = value;
                    this.RaisePropertyChanged("_Ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _Dien_Thoai {
            get {
                return this._Dien_ThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this._Dien_ThoaiField, value) != true)) {
                    this._Dien_ThoaiField = value;
                    this.RaisePropertyChanged("_Dien_Thoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _Mail {
            get {
                return this._MailField;
            }
            set {
                if ((object.ReferenceEquals(this._MailField, value) != true)) {
                    this._MailField = value;
                    this.RaisePropertyChanged("_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _Dia_Chi {
            get {
                return this._Dia_ChiField;
            }
            set {
                if ((object.ReferenceEquals(this._Dia_ChiField, value) != true)) {
                    this._Dia_ChiField = value;
                    this.RaisePropertyChanged("_Dia_Chi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessServiceRef.BusinessServiceSoap")]
    public interface BusinessServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponse HelloWorld(UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponse> HelloWorldAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thay_Doi_Gia_Phong", ReplyAction="*")]
        bool Thay_Doi_Gia_Phong(int _ID, int _Don_Gia_Moi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thay_Doi_Gia_Phong", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Thay_Doi_Gia_PhongAsync(int _ID, int _Don_Gia_Moi);
        
        // CODEGEN: Generating message contract since element name Tim_Loai_Phong_Theo_IDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tim_Loai_Phong_Theo_ID", ReplyAction="*")]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponse Tim_Loai_Phong_Theo_ID(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tim_Loai_Phong_Theo_ID", ReplyAction="*")]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponse> Tim_Loai_Phong_Theo_IDAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu_Nam", ReplyAction="*")]
        double Tinh_Doanh_Thu_Nam(int Nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu_Nam", ReplyAction="*")]
        System.Threading.Tasks.Task<double> Tinh_Doanh_Thu_NamAsync(int Nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu_Thang", ReplyAction="*")]
        double Tinh_Doanh_Thu_Thang(int Thang, int Nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu_Thang", ReplyAction="*")]
        System.Threading.Tasks.Task<double> Tinh_Doanh_Thu_ThangAsync(int Thang, int Nam);
        
        // CODEGEN: Generating message contract since element name Tinh_Doanh_Thu_Loai_PhongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu_Loai_Phong", ReplyAction="*")]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponse Tinh_Doanh_Thu_Loai_Phong(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu_Loai_Phong", ReplyAction="*")]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponse> Tinh_Doanh_Thu_Loai_PhongAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest request);
        
        // CODEGEN: Generating message contract since element name Tinh_Doanh_ThuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu", ReplyAction="*")]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponse Tinh_Doanh_Thu(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tinh_Doanh_Thu", ReplyAction="*")]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponse> Tinh_Doanh_ThuAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest request);
        
        // CODEGEN: Generating message contract since element name Tim_Phong_Theo_IDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tim_Phong_Theo_ID", ReplyAction="*")]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponse Tim_Phong_Theo_ID(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tim_Phong_Theo_ID", ReplyAction="*")]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponse> Tim_Phong_Theo_IDAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest request);
        
        // CODEGEN: Generating message contract since element name _Ten_Dang_Nhap from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kiem_Tra_Dang_Nhap", ReplyAction="*")]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponse Kiem_Tra_Dang_Nhap(UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kiem_Tra_Dang_Nhap", ReplyAction="*")]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponse> Kiem_Tra_Dang_NhapAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest request);
        
        // CODEGEN: Generating message contract since element name Thong_Tin_Khach_SanResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thong_Tin_Khach_San", ReplyAction="*")]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponse Thong_Tin_Khach_San(UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thong_Tin_Khach_San", ReplyAction="*")]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponse> Thong_Tin_Khach_SanAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tim_Loai_Phong_Theo_IDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tim_Loai_Phong_Theo_ID", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequestBody Body;
        
        public Tim_Loai_Phong_Theo_IDRequest() {
        }
        
        public Tim_Loai_Phong_Theo_IDRequest(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tim_Loai_Phong_Theo_IDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int _ID;
        
        public Tim_Loai_Phong_Theo_IDRequestBody() {
        }
        
        public Tim_Loai_Phong_Theo_IDRequestBody(int _ID) {
            this._ID = _ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tim_Loai_Phong_Theo_IDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tim_Loai_Phong_Theo_IDResponse", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponseBody Body;
        
        public Tim_Loai_Phong_Theo_IDResponse() {
        }
        
        public Tim_Loai_Phong_Theo_IDResponse(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tim_Loai_Phong_Theo_IDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CLoaiPhong Tim_Loai_Phong_Theo_IDResult;
        
        public Tim_Loai_Phong_Theo_IDResponseBody() {
        }
        
        public Tim_Loai_Phong_Theo_IDResponseBody(UD_Quan_Ly_Khach_San.BusinessServiceRef.CLoaiPhong Tim_Loai_Phong_Theo_IDResult) {
            this.Tim_Loai_Phong_Theo_IDResult = Tim_Loai_Phong_Theo_IDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tinh_Doanh_Thu_Loai_PhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tinh_Doanh_Thu_Loai_Phong", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequestBody Body;
        
        public Tinh_Doanh_Thu_Loai_PhongRequest() {
        }
        
        public Tinh_Doanh_Thu_Loai_PhongRequest(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tinh_Doanh_Thu_Loai_PhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Thang;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Nam;
        
        public Tinh_Doanh_Thu_Loai_PhongRequestBody() {
        }
        
        public Tinh_Doanh_Thu_Loai_PhongRequestBody(int Thang, int Nam) {
            this.Thang = Thang;
            this.Nam = Nam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tinh_Doanh_Thu_Loai_PhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tinh_Doanh_Thu_Loai_PhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponseBody Body;
        
        public Tinh_Doanh_Thu_Loai_PhongResponse() {
        }
        
        public Tinh_Doanh_Thu_Loai_PhongResponse(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tinh_Doanh_Thu_Loai_PhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.ArrayOfDouble Tinh_Doanh_Thu_Loai_PhongResult;
        
        public Tinh_Doanh_Thu_Loai_PhongResponseBody() {
        }
        
        public Tinh_Doanh_Thu_Loai_PhongResponseBody(UD_Quan_Ly_Khach_San.BusinessServiceRef.ArrayOfDouble Tinh_Doanh_Thu_Loai_PhongResult) {
            this.Tinh_Doanh_Thu_Loai_PhongResult = Tinh_Doanh_Thu_Loai_PhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tinh_Doanh_ThuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tinh_Doanh_Thu", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequestBody Body;
        
        public Tinh_Doanh_ThuRequest() {
        }
        
        public Tinh_Doanh_ThuRequest(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tinh_Doanh_ThuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Nam;
        
        public Tinh_Doanh_ThuRequestBody() {
        }
        
        public Tinh_Doanh_ThuRequestBody(int Nam) {
            this.Nam = Nam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tinh_Doanh_ThuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tinh_Doanh_ThuResponse", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponseBody Body;
        
        public Tinh_Doanh_ThuResponse() {
        }
        
        public Tinh_Doanh_ThuResponse(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tinh_Doanh_ThuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CDoanhThuThang[] Tinh_Doanh_ThuResult;
        
        public Tinh_Doanh_ThuResponseBody() {
        }
        
        public Tinh_Doanh_ThuResponseBody(UD_Quan_Ly_Khach_San.BusinessServiceRef.CDoanhThuThang[] Tinh_Doanh_ThuResult) {
            this.Tinh_Doanh_ThuResult = Tinh_Doanh_ThuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tim_Phong_Theo_IDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tim_Phong_Theo_ID", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequestBody Body;
        
        public Tim_Phong_Theo_IDRequest() {
        }
        
        public Tim_Phong_Theo_IDRequest(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tim_Phong_Theo_IDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int _ID;
        
        public Tim_Phong_Theo_IDRequestBody() {
        }
        
        public Tim_Phong_Theo_IDRequestBody(int _ID) {
            this._ID = _ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tim_Phong_Theo_IDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tim_Phong_Theo_IDResponse", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponseBody Body;
        
        public Tim_Phong_Theo_IDResponse() {
        }
        
        public Tim_Phong_Theo_IDResponse(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tim_Phong_Theo_IDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CPhong Tim_Phong_Theo_IDResult;
        
        public Tim_Phong_Theo_IDResponseBody() {
        }
        
        public Tim_Phong_Theo_IDResponseBody(UD_Quan_Ly_Khach_San.BusinessServiceRef.CPhong Tim_Phong_Theo_IDResult) {
            this.Tim_Phong_Theo_IDResult = Tim_Phong_Theo_IDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Kiem_Tra_Dang_NhapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kiem_Tra_Dang_Nhap", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequestBody Body;
        
        public Kiem_Tra_Dang_NhapRequest() {
        }
        
        public Kiem_Tra_Dang_NhapRequest(UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Kiem_Tra_Dang_NhapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _Ten_Dang_Nhap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _Mat_Khau;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _Loai_Nhan_Vien;
        
        public Kiem_Tra_Dang_NhapRequestBody() {
        }
        
        public Kiem_Tra_Dang_NhapRequestBody(string _Ten_Dang_Nhap, string _Mat_Khau, string _Loai_Nhan_Vien) {
            this._Ten_Dang_Nhap = _Ten_Dang_Nhap;
            this._Mat_Khau = _Mat_Khau;
            this._Loai_Nhan_Vien = _Loai_Nhan_Vien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Kiem_Tra_Dang_NhapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kiem_Tra_Dang_NhapResponse", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponseBody Body;
        
        public Kiem_Tra_Dang_NhapResponse() {
        }
        
        public Kiem_Tra_Dang_NhapResponse(UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Kiem_Tra_Dang_NhapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Kiem_Tra_Dang_NhapResult;
        
        public Kiem_Tra_Dang_NhapResponseBody() {
        }
        
        public Kiem_Tra_Dang_NhapResponseBody(bool Kiem_Tra_Dang_NhapResult) {
            this.Kiem_Tra_Dang_NhapResult = Kiem_Tra_Dang_NhapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Thong_Tin_Khach_SanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Thong_Tin_Khach_San", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequestBody Body;
        
        public Thong_Tin_Khach_SanRequest() {
        }
        
        public Thong_Tin_Khach_SanRequest(UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Thong_Tin_Khach_SanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int _ID;
        
        public Thong_Tin_Khach_SanRequestBody() {
        }
        
        public Thong_Tin_Khach_SanRequestBody(int _ID) {
            this._ID = _ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Thong_Tin_Khach_SanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Thong_Tin_Khach_SanResponse", Namespace="http://tempuri.org/", Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponseBody Body;
        
        public Thong_Tin_Khach_SanResponse() {
        }
        
        public Thong_Tin_Khach_SanResponse(UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Thong_Tin_Khach_SanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CKhachSan Thong_Tin_Khach_SanResult;
        
        public Thong_Tin_Khach_SanResponseBody() {
        }
        
        public Thong_Tin_Khach_SanResponseBody(UD_Quan_Ly_Khach_San.BusinessServiceRef.CKhachSan Thong_Tin_Khach_SanResult) {
            this.Thong_Tin_Khach_SanResult = Thong_Tin_Khach_SanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessServiceSoapChannel : UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceSoapClient : System.ServiceModel.ClientBase<UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap>, UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap {
        
        public BusinessServiceSoapClient() {
        }
        
        public BusinessServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponse UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.HelloWorld(UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequestBody();
            UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponse retVal = ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponse> UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.HelloWorldAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldResponse> HelloWorldAsync() {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.HelloWorldRequestBody();
            return ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public bool Thay_Doi_Gia_Phong(int _ID, int _Don_Gia_Moi) {
            return base.Channel.Thay_Doi_Gia_Phong(_ID, _Don_Gia_Moi);
        }
        
        public System.Threading.Tasks.Task<bool> Thay_Doi_Gia_PhongAsync(int _ID, int _Don_Gia_Moi) {
            return base.Channel.Thay_Doi_Gia_PhongAsync(_ID, _Don_Gia_Moi);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponse UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tim_Loai_Phong_Theo_ID(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest request) {
            return base.Channel.Tim_Loai_Phong_Theo_ID(request);
        }
        
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CLoaiPhong Tim_Loai_Phong_Theo_ID(int _ID) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequestBody();
            inValue.Body._ID = _ID;
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponse retVal = ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tim_Loai_Phong_Theo_ID(inValue);
            return retVal.Body.Tim_Loai_Phong_Theo_IDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponse> UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tim_Loai_Phong_Theo_IDAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest request) {
            return base.Channel.Tim_Loai_Phong_Theo_IDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDResponse> Tim_Loai_Phong_Theo_IDAsync(int _ID) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Loai_Phong_Theo_IDRequestBody();
            inValue.Body._ID = _ID;
            return ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tim_Loai_Phong_Theo_IDAsync(inValue);
        }
        
        public double Tinh_Doanh_Thu_Nam(int Nam) {
            return base.Channel.Tinh_Doanh_Thu_Nam(Nam);
        }
        
        public System.Threading.Tasks.Task<double> Tinh_Doanh_Thu_NamAsync(int Nam) {
            return base.Channel.Tinh_Doanh_Thu_NamAsync(Nam);
        }
        
        public double Tinh_Doanh_Thu_Thang(int Thang, int Nam) {
            return base.Channel.Tinh_Doanh_Thu_Thang(Thang, Nam);
        }
        
        public System.Threading.Tasks.Task<double> Tinh_Doanh_Thu_ThangAsync(int Thang, int Nam) {
            return base.Channel.Tinh_Doanh_Thu_ThangAsync(Thang, Nam);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponse UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tinh_Doanh_Thu_Loai_Phong(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest request) {
            return base.Channel.Tinh_Doanh_Thu_Loai_Phong(request);
        }
        
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.ArrayOfDouble Tinh_Doanh_Thu_Loai_Phong(int Thang, int Nam) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequestBody();
            inValue.Body.Thang = Thang;
            inValue.Body.Nam = Nam;
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponse retVal = ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tinh_Doanh_Thu_Loai_Phong(inValue);
            return retVal.Body.Tinh_Doanh_Thu_Loai_PhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponse> UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tinh_Doanh_Thu_Loai_PhongAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest request) {
            return base.Channel.Tinh_Doanh_Thu_Loai_PhongAsync(request);
        }
        
        public System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongResponse> Tinh_Doanh_Thu_Loai_PhongAsync(int Thang, int Nam) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_Thu_Loai_PhongRequestBody();
            inValue.Body.Thang = Thang;
            inValue.Body.Nam = Nam;
            return ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tinh_Doanh_Thu_Loai_PhongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponse UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tinh_Doanh_Thu(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest request) {
            return base.Channel.Tinh_Doanh_Thu(request);
        }
        
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CDoanhThuThang[] Tinh_Doanh_Thu(int Nam) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequestBody();
            inValue.Body.Nam = Nam;
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponse retVal = ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tinh_Doanh_Thu(inValue);
            return retVal.Body.Tinh_Doanh_ThuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponse> UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tinh_Doanh_ThuAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest request) {
            return base.Channel.Tinh_Doanh_ThuAsync(request);
        }
        
        public System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuResponse> Tinh_Doanh_ThuAsync(int Nam) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tinh_Doanh_ThuRequestBody();
            inValue.Body.Nam = Nam;
            return ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tinh_Doanh_ThuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponse UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tim_Phong_Theo_ID(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest request) {
            return base.Channel.Tim_Phong_Theo_ID(request);
        }
        
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CPhong Tim_Phong_Theo_ID(int _ID) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequestBody();
            inValue.Body._ID = _ID;
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponse retVal = ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tim_Phong_Theo_ID(inValue);
            return retVal.Body.Tim_Phong_Theo_IDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponse> UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Tim_Phong_Theo_IDAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest request) {
            return base.Channel.Tim_Phong_Theo_IDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDResponse> Tim_Phong_Theo_IDAsync(int _ID) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Tim_Phong_Theo_IDRequestBody();
            inValue.Body._ID = _ID;
            return ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Tim_Phong_Theo_IDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponse UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Kiem_Tra_Dang_Nhap(UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest request) {
            return base.Channel.Kiem_Tra_Dang_Nhap(request);
        }
        
        public bool Kiem_Tra_Dang_Nhap(string _Ten_Dang_Nhap, string _Mat_Khau, string _Loai_Nhan_Vien) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequestBody();
            inValue.Body._Ten_Dang_Nhap = _Ten_Dang_Nhap;
            inValue.Body._Mat_Khau = _Mat_Khau;
            inValue.Body._Loai_Nhan_Vien = _Loai_Nhan_Vien;
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponse retVal = ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Kiem_Tra_Dang_Nhap(inValue);
            return retVal.Body.Kiem_Tra_Dang_NhapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponse> UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Kiem_Tra_Dang_NhapAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest request) {
            return base.Channel.Kiem_Tra_Dang_NhapAsync(request);
        }
        
        public System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapResponse> Kiem_Tra_Dang_NhapAsync(string _Ten_Dang_Nhap, string _Mat_Khau, string _Loai_Nhan_Vien) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Kiem_Tra_Dang_NhapRequestBody();
            inValue.Body._Ten_Dang_Nhap = _Ten_Dang_Nhap;
            inValue.Body._Mat_Khau = _Mat_Khau;
            inValue.Body._Loai_Nhan_Vien = _Loai_Nhan_Vien;
            return ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Kiem_Tra_Dang_NhapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponse UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Thong_Tin_Khach_San(UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest request) {
            return base.Channel.Thong_Tin_Khach_San(request);
        }
        
        public UD_Quan_Ly_Khach_San.BusinessServiceRef.CKhachSan Thong_Tin_Khach_San(int _ID) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequestBody();
            inValue.Body._ID = _ID;
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponse retVal = ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Thong_Tin_Khach_San(inValue);
            return retVal.Body.Thong_Tin_Khach_SanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponse> UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap.Thong_Tin_Khach_SanAsync(UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest request) {
            return base.Channel.Thong_Tin_Khach_SanAsync(request);
        }
        
        public System.Threading.Tasks.Task<UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanResponse> Thong_Tin_Khach_SanAsync(int _ID) {
            UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest inValue = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequest();
            inValue.Body = new UD_Quan_Ly_Khach_San.BusinessServiceRef.Thong_Tin_Khach_SanRequestBody();
            inValue.Body._ID = _ID;
            return ((UD_Quan_Ly_Khach_San.BusinessServiceRef.BusinessServiceSoap)(this)).Thong_Tin_Khach_SanAsync(inValue);
        }
    }
}
